/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author 51934
 */
public class frmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);


    }

    public JLabel getBtnCliente() {
        return btnCliente;
    }

    public void setBtnCliente(JLabel btnCliente) {
        this.btnCliente = btnCliente;
    }

    public JLabel getBtnEmpleado() {
        return btnEmpleado;
    }

    public void setBtnEmpleado(JLabel btnEmpleado) {
        this.btnEmpleado = btnEmpleado;
    }

    public JLabel getBtnProducto() {
        return btnProducto;
    }

    public void setBtnProducto(JLabel btnProducto) {
        this.btnProducto = btnProducto;
    }

    public JLabel getBtnVentas() {
        return btnVentas;
    }

    public void setBtnVentas(JLabel btnVentas) {
        this.btnVentas = btnVentas;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    
    private void hover(JLabel btn,String opcion){
        JLabel[] botons = {btnEmpleado,btnCliente,btnProducto,btnVentas};
        switch(opcion){
            case "HOVER":
                for(JLabel b: botons){
                    if(btn.equals(b)){
                        btn.setForeground(Color.white);
                        btn.setFont(new Font("Dialog",0,20));
                        break;
                    }
                }
                break;
            default:
                for(JLabel b: botons){
                    if(btn.equals(b)){
                        btn.setForeground(new Color(204,204,204));
                        btn.setFont(new Font("Dialog",0,18));
                    }
                }
                break;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnProducto = new javax.swing.JLabel();
        btnEmpleado = new javax.swing.JLabel();
        btnCliente = new javax.swing.JLabel();
        btnVentas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(32, 29, 29));
        jPanel2.setMaximumSize(new java.awt.Dimension(240, 1500));
        jPanel2.setMinimumSize(new java.awt.Dimension(240, 1090));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 1090));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(204, 204, 204));
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProducto.setText("PRODUCTO");
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductoMouseExited(evt);
            }
        });
        jPanel2.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 228, 36));

        btnEmpleado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(204, 204, 204));
        btnEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmpleado.setText("EMPLEADO");
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseExited(evt);
            }
        });
        jPanel2.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 186, 250, 36));

        btnCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCliente.setText("CLIENTE");
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
        });
        jPanel2.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 332, 228, 36));

        btnVentas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(204, 204, 204));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentas.setText("VENTAS");
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 410, 228, 36));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VentasCM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 228, 36));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -430;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(45, 45, 45));

        escritorio.setBackground(new java.awt.Color(45, 45, 45));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 770;
        gridBagConstraints.ipady = 660;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseEntered
        // TODO add your handling code here:
        hover(btnEmpleado, "HOVER");
    }//GEN-LAST:event_btnEmpleadoMouseEntered

    private void btnEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseExited
        // TODO add your handling code here:
        hover(btnEmpleado, "NO");
    }//GEN-LAST:event_btnEmpleadoMouseExited

    private void btnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseEntered
        // TODO add your handling code here:
        hover(btnProducto, "HOVER");
    }//GEN-LAST:event_btnProductoMouseEntered

    private void btnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseExited
        // TODO add your handling code here:
        hover(btnProducto, "NO");
    }//GEN-LAST:event_btnProductoMouseExited

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        // TODO add your handling code here:
        hover(btnCliente, "HOVER");
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        // TODO add your handling code here:
        hover(btnCliente, "NO");
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        // TODO add your handling code here:
        hover(btnVentas, "HOVER");
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        // TODO add your handling code here:
        hover(btnVentas, "NO");
    }//GEN-LAST:event_btnVentasMouseExited

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCliente;
    private javax.swing.JLabel btnEmpleado;
    private javax.swing.JLabel btnProducto;
    private javax.swing.JLabel btnVentas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
